variables:
  IMAGE: "gcr.io/rentspree-6789/devspree-covid-close-contact-api"
  CLUSTER: "devspree --zone asia-southeast1-a --project rentspree-6789"
  MONGO_IMAGE: "mongo:4.2"
  SERVICE_NAME: "covid"

include:
  - project: 'rentspree/utility/ci-template'
    file: '/template.yaml'
    ref: 'latest'
#  - project: 'rentspree/utility/ci-template'
#    file: '/test-service.yaml'
#    ref: 'latest'
