apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-spree-service
  namespace: covid-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: covid-spree-service
        config_map: "true"
    spec:
      containers:
        - name: covid-spree-service
          image: {{IMAGE}}
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: NODE_ENV
              value: "production"
            - name: MONGO_DB
              value: "covid-spree-mongo"
          envFrom:
            - configMapRef:
                name: covid-spree-config
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: jwt-auth-secret
              readOnly: true
              mountPath: "/app/certs"
            - name: gcloud-storage-key
              readOnly: true
              mountPath: "/app/private-key"
      volumes:
        - name: jwt-auth-secret
          secret:
            secretName: jwt-auth-secret
        - name: gcloud-storage-key
          secret:
            secretName: gcloud-storage-key
  selector:
    matchLabels:
      app: covid-spree-service
